会場変更Update venue
mkanda1955/ichiyasaGitSample pull request #1
Opened 2024-05-08 09:59 UTC by mkanda1955

会場２回変更

2024-05-09 09:17 UTC, kanda0313 commented
会場変更有難うございます。

2024-05-09 09:19 UTC, kanda0313 commented
会場　再変更有難うございます。

2024-05-09 09:28 UTC, kanda0313 commented
![LGTM](https://github.com/mkanda1955/ichiyasaGitSample/assets/169007337/a1d0f1e6-c521-43cc-a307-ccce4812a921)

2024-05-09 10:21 UTC, kanda0313 requested changes
指摘の確認と修正をお願いします。

2024-05-09 10:21 UTC, kanda0313 commented on index.html
> +                        <p>株式会社インプレス・アネックス イベントセミナー会場</p>
「株式会社インプレス」と正式な表記にしていただけますか？

2024-05-09 10:21 UTC, kanda0313 commented on index.html
> +                        <p>株式会社インプレス・アネックス イベントセミナー会場</p>
追加コメント

2024-05-12 02:08 UTC, kanda0313 requested changes

2024-05-12 02:08 UTC, kanda0313 commented on index.html
> +                        <p>       18:00開場</p>
会場時刻へのコメント

2024-05-12 02:08 UTC, kanda0313 commented on index.html
>                          <h3>イベント日時・場所</h3>
イベント日時に雨天決行をいれる

2024-05-12 02:25 UTC, mkanda1955 commented
修正しました。

2024-05-12 02:26 UTC, kanda0313 approved these changes

2024-05-12 03:35 UTC, merged